services:

  formatif-dev-container:
    container_name: formatif-dev-container
    image: lmsdoubtfire/formatif-devcontainer:8.3-dev
    build:
      context: ../
      dockerfile: dev.Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
      - formatif_tmp_compose:/workspace/tmp
      - formatif_student-work_compose:/student-work
      - ws_node_modules:/workspace/node_modules
      - web_node_modules:/workspace/doubtfire-web/node_modules
      - formatif_db_compose:/var/lib/mysql
      - formatif_gems_compose:/home/vscode/.gems
    ports:
      - "9876:9876"
      - "4200:4200"
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 5000; do :; done"
    env_file:
      - ./devcontainer.env
    networks:
      - default

  # This is the proxy which receives all http requests and forwards to relevant servers.
  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    expose:
      - 80:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy-nginx.conf:/etc/nginx/nginx.conf
      # - ./localhost.crt:/etc/nginx/cert.crt # replace with real certificate
      # - ./localhost.key:/etc/nginx/key.key # replace with real key
    restart: on-failure:2
    env_file:
      - ./devcontainer.env
    networks:
      - default

  # Database server - could be external to docker
  doubtfire-db:
    image: mariadb:10
    platform: linux/amd64
    build:
      context: ../
      dockerfile: dev.Dockerfile
    depends_on:
      - formatif-dev-container
      - proxy
    volumes:
      - ./:/workspace/.devcontainer/
      - mysql_db:/var/lib/mysql
    env_file:
      - ./devcontainer.env
    networks:
      - default
    ports:
      - "3306:3306"

  redis-sidekiq:
    container_name: doubtfire-redis-sidekiq
    image: redis:7.0
    volumes:
      - redis_sidekiq_data:/data
    env_file:
      - ./devcontainer.env
    networks:
      - default


networks:
  default:
    driver: bridge

volumes:
  ws_node_modules:
  web_node_modules:
  formatif_tmp_compose:
  formatif_student-work_compose:
  formatif_db_compose:
  formatif_gems_compose:
  redis_sidekiq_data:
  doubtfire_logs: {}
  mysql_db: {}
  student_work: {}
